export const GET_DONORS_LIST_SUCCESS = "GET_DONORS_LIST_SUCCESS";
export const GET_DONORS_LIST_FAILURE = "GET_DONORS_LIST_FAILURE";

export const DELETE_DONOR_SUCCESS = "DELETE_DONOR_SUCCESS";
export const DELETE_DONOR_FAILURE = "DELETE_DONOR_FAILURE";

export const APPROVE_DECLINE_CHARITY_REQUEST_SUCCESS = "APPROVE_DECLINE_CHARITY_REQUEST_SUCCESS";
export const APPROVE_DECLINE_CHARITY_REQUEST_FAILURE = "APPROVE_DECLINE_CHARITY_REQUEST_FAILURE";


export const ADD_EDIT_DONOR_SUCCESS = "ADD_EDIT_DONOR_SUCCESS";
export const ADD_EDIT_DONOR_FAILURE = "ADD_EDIT_DONOR_FAILURE";

export const GET_PHONE_CODE_SUCCESS = "GET_COUNTRY_CODE_SUCCESS";
export const GET_PHONE_CODE_FAILURE = "GET_COUNTRY_CODE_FAILURE";