export const SEND_OTP_SUCCESS = "SEND_OTP_SUCCESS";
export const SEND_OTP_FAILURE = "SEND_OTP_FAILURE";

export const FORGET_PASSWORD_VERIFY_OTP_SUCCESS = "FORGET_PASSWORD_VERIFY_OTP_SUCCESS";
export const FORGET_PASSWORD_VERIFY_OTP_FAILURE = "FORGET_PASSWORD_VERIFY_OTP_FAILURE";

export const ADD_NEW_PASSWORD_SUCCESS = "ADD_NEW_PASSWORD_SUCCESS";
export const ADD_NEW_PASSWORD_FAILURE = "ADD_NEW_PASSWORD_FAILURE";

