export const CHARITY_NAME_REQUIRED = 'Charity Name is Required!';
export const CHARITY_COLOR_REQUIRED = 'Charity Color is Required!';
export const CHARITY_STATUS_REQUIRED = 'Charity Status is Required!';
export const PLEASE_PROVIDE_VALID_LINK = 'Please Provide valid Link!';
export const GOAL_AMOUNT_REQUIRED = 'Goal Amount is Required!';
export const MONTHLY_AMOUNT_REQUIRED = 'Monthly Amount is Required!';
export const ONLY_NUMBER_VALIDATION = "Please Enter a only Number.";
export const FILE_SIZE_VALIDATION = 'Uploaded file is too big.';
export const FILE_FORMATE_VALIDATION = 'Uploaded file has unsupported format.';